import {
  AccountCircle as User,
  AccountCircleOutlined as UserOutline,
  Assessment as Reports,
  AssessmentOutlined as ReportsOutline,
  Block as Cancel,
  Checklist,
  ChevronLeft as Left,
  ChevronRight as Right,
  Clear,
  Close,
  Cloud,
  CloudOutlined,
  CloudDone,
  CloudOff,
  Comment,
  CommentOutlined,
  Delete,
  Dns as Db,
  DnsOutlined as DbOutline,
  Download,
  Edit,
  Email,
  Help,
  HelpOutlined as HelpOutline,
  Key as Secret,
  Login,
  Logout,
  MoreHoriz as More,
  People as Users,
  PeopleOutlined as UsersOutline,
  Power,
  PowerOutlined as PowerOutline,
  Publish as Upload,
  RadioButtonUnchecked as Unchecked,
  Save,
  Search,
  Settings,
  SettingsOutlined as SettingsOutline,
  AddCircleOutlined as Add,
  CheckCircleOutlined as Checked,
} from '@mui/icons-material';

const Icon = {
  Add,
  Cancel,
  Checked,
  Unchecked,
  Checklist,
  Clear,
  Close,
  Cloud,
  CloudOutlined,
  CloudDone,
  CloudOff,
  Comment,
  CommentOutlined,
  Db,
  DbOutline,
  Delete,
  Download,
  Edit,
  Email,
  Help,
  HelpOutline,
  Left,
  Right,
  Login,
  Logout,
  More,
  Power,
  PowerOutline,
  Reports,
  ReportsOutline,
  Save,
  Search,
  Secret,
  Settings,
  SettingsOutline,
  Upload,
  User,
  UserOutline,
  Users,
  UsersOutline,
};
export default Icon;
